version: '3.8'

services:
  web:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
    networks:
      - backend

  mongo:
    image: "mongo:latest"
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  redis:
    image: "redis:alpine"
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
